version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: maxpadget/kittygram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/
    command: gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000

  frontend:
    image: maxpadget/kittygram_frontend:latest
    volumes:
      - static:/static/
    command: sh -c "cp -r /app/build/. /static/"

  gateway:
    image: maxpadget/kittygram_gateway:latest
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend