volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: maxpadget/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - media_volume:/app/media
      - static_volume:/app/collected_static

  frontend:
    image: maxpadget/kittygram_frontend
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/static

  gateway:
    image: maxpadget/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media_volume:/media