server {
    listen 80;
    server_name kittygram-maksi.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kittygram-maksi.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/kittygram-maksi.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kittygram-maksi.duckdns.org/privkey.pem;

    # ВСЁ через gateway
    location / {
        proxy_pass http://127.0.0.1:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:9000;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:9000;
    }

    location /static/ {
        alias /var/www/kittygram/static/;
    }

    location /media/ {
        alias /var/www/kittygram/media/;
    }
}

server {
    listen 80;
    server_name taski-maksi.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name taski-maksi.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/taski-maksi.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taski-maksi.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location /static/ {
        alias /var/www/taski/static/;
    }

    location /media/ {
        alias /var/www/taski/media/;
    }
}