upstream kittygram_backend {
    server backend:8000;
}

upstream taski_backend {
    server taski-backend:8000;
}

server {
    listen 80;
    server_tokens off;
    server_name kittygram-maksi.duckdns.org;

    location /api/ {
        proxy_pass http://kittygram_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://kittygram_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /media/ {
        alias /media/;
    }

    location /static/ {
        alias /static/;
    }

    location / {
        root /static;
        index index.html index.htm;
        try_files $uri /index.html;
    }
}

server {
    listen 80;
    server_tokens off;
    server_name taski-maksi.duckdns.org;

    location /api/ {
        proxy_pass http://taski_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://taski_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /taski-static/;
    }

    location / {
        root /taski-static;
        index index.html index.htm;
        try_files $uri /index.html;
    }
}